### ISSUE TITLE
When running the training code, the video memory always explodes    在跑训练代码的时候总是爆显存

### ISSUE THREAD

**Issue by szl-BUPT** [mi150/RegenHance#3]
During the training code, the video memory exploded. Even with an H20 graphics card with 96GB of video memory, only more than 300 data sets could be trained.After monitoring, the video memory seemed to be increasing and not being released.

在训练代码过程中出现显存爆炸的现象，即使是用96GB显存的H20显卡都只能训练300多张数据集，经过监控显存貌似一直在递增没有被释放

torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 150.00 MiB. GPU 0 has a total capacty of 95.10 GiB of which 115.81 MiB is free. Including non-PyTorch memory, this process has 94.98 GiB memory in use. Of the allocated memory 92.76 GiB is allocated by PyTorch, and 1.70 GiB is reserved by PyTorch but unallocated. If reserved but unallocated memory is large try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF

Generating saliency as ground truths  18%|███████████████████▏                                                                                       |  388/2177 [01:26<06:34, 4.54 frames/s]

**Comment by censhallwe** [comment]
您好，根据目前您提供的信息“Generating saliency as ground truths”，应该是在生成Ground Truth时出现了爆显存的现象。按照[该文档](https://github.com/mi150/RegenHance/blob/main/train/train-cn.md) 中的过程，此时您应该已经提前生成好了超分后的高分辨率图像，并保存在了相应的目录下。
如果上述步骤没有问题的话，我个人猜测可能是超分后图片的分辨率过大导致的。我当时在整理代码复现流程时，采用的超分倍率是360p -> 1080p，用的是80G显存的A800。您可以尝试降低batch size看看是否能有帮助。
由于根据目前您提供的信息我暂时只能想到这些，如果可以的话，方便详述一下您在复现时的环境、过程等相关信息吗？
抱歉给您带来了困扰，如果还是遇到上述问题的话，欢迎随时联系并@我，我将会在24小时内进行回复。 @szl-BUPT

**Comment by szl-BUPT** [comment]
非常感谢您的回复！我使用的超分倍率是360p->720p（按理说需要的显存还会小一些）,用的是96GB显存的H20显卡，按照您教程中的步骤指示准备了数据集文件，同时修改了720p所对应的参数。我尝试了降低batch size，但是感觉降低前与降低后的表现没有区别，我用24G的显卡能训练4%的数据，32G的显卡能跑7%的数据，96GB的显卡最多跑到18%，监控的时候我看到显存好像一直在被申请，最后就会爆掉。于是有些疑惑就来提问了，感谢您非常及时的回复，不知道在您那里会不会出现显存不释放，占用率累计增大的问题，但是因为够大cover住了。如果您那边没有的话应该是我这边部署的问题，如果有的话我也许需要优化一下显存释放这一块，您也许可以帮我定位一下问题。
我接下来将尝试用您的原生教程中的1080p试验一下。总之，感谢您的回复！

> 您好，根据目前您提供的信息“Generating saliency as ground truths”，应该是在生成Ground Truth时出现了爆显存的现象。按照[该文档](https://github.com/mi150/RegenHance/blob/main/train/train-cn.md) 中的过程，此时您应该已经提前生成好了超分后的高分辨率图像，并保存在了相应的目录下。 如果上述步骤没有问题的话，我个人猜测可能是超分后图片的分辨率过大导致的。我当时在整理代码复现流程时，采用的超分倍率是360p -> 1080p，用的是80G显存的A800。您可以尝试降低batch size看看是否能有帮助。 由于根据目前您提供的信息我暂时只能想到这些，如果可以的话，方便详述一下您在复现时的环境、过程等相关信息吗？ 抱歉给您带来了困扰，如果还是遇到上述问题的话，欢迎随时联系并@我，我将会在24小时内进行回复。 [@szl-BUPT](https://github.com/szl-BUPT)

**Comment by censhallwe** [comment]
> 非常感谢您的回复！我使用的超分倍率是360p->720p（按理说需要的显存还会小一些）,用的是96GB显存的H20显卡，按照您教程中的步骤指示准备了数据集文件，同时修改了720p所对应的参数。我尝试了降低batch size，但是感觉降低前与降低后的表现没有区别，我用24G的显卡能训练4%的数据，32G的显卡能跑7%的数据，96GB的显卡最多跑到18%，监控的时候我看到显存好像一直在被申请，最后就会爆掉。于是有些疑惑就来提问了，感谢您非常及时的回复，不知道在您那里会不会出现显存不释放，占用率累计增大的问题，但是因为够大cover住了。如果您那边没有的话应该是我这边部署的问题，如果有的话我也许需要优化一下显存释放这一块，您也许可以帮我定位一下问题。 我接下来将尝试用您的原生教程中的1080p试验一下。总之，感谢您的回复！
> 
> > 您好，根据目前您提供的信息“Generating saliency as ground truths”，应该是在生成Ground Truth时出现了爆显存的现象。按照[该文档](https://github.com/mi150/RegenHance/blob/main/train/train-cn.md) 中的过程，此时您应该已经提前生成好了超分后的高分辨率图像，并保存在了相应的目录下。 如果上述步骤没有问题的话，我个人猜测可能是超分后图片的分辨率过大导致的。我当时在整理代码复现流程时，采用的超分倍率是360p -> 1080p，用的是80G显存的A800。您可以尝试降低batch size看看是否能有帮助。 由于根据目前您提供的信息我暂时只能想到这些，如果可以的话，方便详述一下您在复现时的环境、过程等相关信息吗？ 抱歉给您带来了困扰，如果还是遇到上述问题的话，欢迎随时联系并@我，我将会在24小时内进行回复。 [@szl-BUPT](https://github.com/szl-BUPT)

了解到了，确实按理说显存资源应该不会那么紧张🤔。你可以尝试在train_AccModel.py中123行mask_grad_ = sr_image.grad.norm(dim=1, p=1, keepdim=True)后面加上`torch.cuda.empty_cache()`清一下显存缓冲区，或者在def get_groundtruths这个方法内部多试着`torch.cuda.empty_cache()`，或许可以缓解显存不足的问题😳

😿抱歉给您带来了不便，感谢您指出了目前项目中的不足，如果后续还是存在上述问题我会试着深入调查一下，另外，遇到其他任何问题也欢迎您随时提出，THX🥳

**Comment by szl-BUPT** [comment]
> > 非常感谢您的回复！我使用的超分倍率是360p->720p（按理说需要的显存还会小一些）,用的是96GB显存的H20显卡，按照您教程中的步骤指示准备了数据集文件，同时修改了720p所对应的参数。我尝试了降低batch size，但是感觉降低前与降低后的表现没有区别，我用24G的显卡能训练4%的数据，32G的显卡能跑7%的数据，96GB的显卡最多跑到18%，监控的时候我看到显存好像一直在被申请，最后就会爆掉。于是有些疑惑就来提问了，感谢您非常及时的回复，不知道在您那里会不会出现显存不释放，占用率累计增大的问题，但是因为够大cover住了。如果您那边没有的话应该是我这边部署的问题，如果有的话我也许需要优化一下显存释放这一块，您也许可以帮我定位一下问题。 我接下来将尝试用您的原生教程中的1080p试验一下。总之，感谢您的回复！
> > > 您好，根据目前您提供的信息“Generating saliency as ground truths”，应该是在生成Ground Truth时出现了爆显存的现象。按照[该文档](https://github.com/mi150/RegenHance/blob/main/train/train-cn.md) 中的过程，此时您应该已经提前生成好了超分后的高分辨率图像，并保存在了相应的目录下。 如果上述步骤没有问题的话，我个人猜测可能是超分后图片的分辨率过大导致的。我当时在整理代码复现流程时，采用的超分倍率是360p -> 1080p，用的是80G显存的A800。您可以尝试降低batch size看看是否能有帮助。 由于根据目前您提供的信息我暂时只能想到这些，如果可以的话，方便详述一下您在复现时的环境、过程等相关信息吗？ 抱歉给您带来了困扰，如果还是遇到上述问题的话，欢迎随时联系并@我，我将会在24小时内进行回复。 [@szl-BUPT](https://github.com/szl-BUPT)
> 
> 了解到了，确实按理说显存资源应该不会那么紧张🤔。你可以尝试在train_AccModel.py中123行mask_grad_ = sr_image.grad.norm(dim=1, p=1, keepdim=True)后面加上`torch.cuda.empty_cache()`清一下显存缓冲区，或者在def get_groundtruths这个方法内部多试着`torch.cuda.empty_cache()`，或许可以缓解显存不足的问题😳
> 
> 😿抱歉给您带来了不便，感谢您指出了目前项目中的不足，如果后续还是存在上述问题我会试着深入调查一下，另外，遇到其他任何问题也欢迎您随时提出，THX🥳

好的感谢，我再试试，有什么进展我也来这里反馈一下~

**Comment by Brave-Maker** [comment]
> > > 非常感谢您的回复！我使用的超分倍率是360p->720p（按理说需要的显存还会小一些）,用的是96GB显存的H20显卡，按照您教程中的步骤指示准备了数据集文件，同时修改了720p所对应的参数。我尝试了降低batch size，但是感觉降低前与降低后的表现没有区别，我用24G的显卡能训练4%的数据，32G的显卡能跑7%的数据，96GB的显卡最多跑到18%，监控的时候我看到显存好像一直在被申请，最后就会爆掉。于是有些疑惑就来提问了，感谢您非常及时的回复，不知道在您那里会不会出现显存不释放，占用率累计增大的问题，但是因为够大cover住了。如果您那边没有的话应该是我这边部署的问题，如果有的话我也许需要优化一下显存释放这一块，您也许可以帮我定位一下问题。 我接下来将尝试用您的原生教程中的1080p试验一下。总之，感谢您的回复！
> > > > 您好，根据目前您提供的信息“Generating saliency as ground truths”，应该是在生成Ground Truth时出现了爆显存的现象。按照[该文档](https://github.com/mi150/RegenHance/blob/main/train/train-cn.md) 中的过程，此时您应该已经提前生成好了超分后的高分辨率图像，并保存在了相应的目录下。 如果上述步骤没有问题的话，我个人猜测可能是超分后图片的分辨率过大导致的。我当时在整理代码复现流程时，采用的超分倍率是360p -> 1080p，用的是80G显存的A800。您可以尝试降低batch size看看是否能有帮助。 由于根据目前您提供的信息我暂时只能想到这些，如果可以的话，方便详述一下您在复现时的环境、过程等相关信息吗？ 抱歉给您带来了困扰，如果还是遇到上述问题的话，欢迎随时联系并@我，我将会在24小时内进行回复。 [@szl-BUPT](https://github.com/szl-BUPT)
> > 
> > 
> > 了解到了，确实按理说显存资源应该不会那么紧张🤔。你可以尝试在train_AccModel.py中123行mask_grad_ = sr_image.grad.norm(dim=1, p=1, keepdim=True)后面加上`torch.cuda.empty_cache()`清一下显存缓冲区，或者在def get_groundtruths这个方法内部多试着`torch.cuda.empty_cache()`，或许可以缓解显存不足的问题😳
> > 😿抱歉给您带来了不便，感谢您指出了目前项目中的不足，如果后续还是存在上述问题我会试着深入调查一下，另外，遇到其他任何问题也欢迎您随时提出，THX🥳
> 
> 好的感谢，我再试试，有什么进展我也来这里反馈一下~

你好，我也遇到了同样的问题，我已经尝试加入了多条`torch.cuda.empty_cache()`语句但仍然不起作用。请问你解决了这个问题吗，如果能给予我一些帮助，我万分感激！
